### ISSUE TITLE
TexSoup is eating spaces

### ISSUE THREAD

**Issue by lmm-git** [alvinwan/TexSoup#107]
Hi,

we encountered the following problem with the latest version of TexSoup:

```python
from TexSoup import TexSoup

text = """
\\begin{document}
\\lstinline{\\- Word [a-z]+}
\\end{document}

"""

def main():
    soup = TexSoup(text)
    print(soup)

if __name__ == '__main__':
    main()

```

Problem is, that the space after `Word` is omitted during string conversion (or loading, I do not know). Stdout for the script above looks like this:

```
\begin{document}
\lstinline{\- Word[a-z]+}
\end{document}
```

Worked as expected with texsoup==0.2.0

**Comment by alvinwan** [comment]
@lmm-git oof thank you for reporting. This is an issue with the new parser -- taking a look now.

**Comment by alvinwan** [comment]
Wow I had no idea this was a valid command. For anyone else curious, it's a [soft hyphen](https://tex.stackexchange.com/questions/453469/what-does-a-backslash-hyphen-do).

This actually reflected a bigger bug in the tokenizer. Amended the tokenizer to handle all non-letter "escaped" sequences (recognized or otherwise) correctly.

**Comment by lmm-git** [comment]
Thanks for fixing this issue!
