### ISSUE TITLE
parsing intervals notations following french conventions

### ISSUE THREAD

**Issue by ntala** [alvinwan/TexSoup#137]
Hello,

In France, intervals notations differ from those adopted in English.
Instead of writing "[0, +\infty)", we write "[0 ; +\infty[".
This kind of notations seems not to be parsed with success by TexSoup.
It is a big problem for me because most of the documents I have to process contain formulas like that.
I tried some workaround few in august. I will try to reorganize and share what I manage to do, but first I leave a short document to reproduce the bug :

```\documentclass{article}
\begin{document}
$[0~;~+ \infty[$.
\end{document}
```

Latex compile this document without problem, but the last opening bracket or the fact the first one should be closed by the second one, break the parsing. TexSoup does not "see" the closing "$". 
This second document is correctly parsed by TexSoup : 
```\documentclass{article}
\begin{document}
$\left[0~;~+ \infty\right[$.
\end{document}
```

Thank you for all the work done and for the help you may give me.

**Comment by ivanistheone** [comment]
> This second document is correctly parsed by TexSoup :
> 
> ```
> \begin{document}
> $\left[0~;~+ \infty\right[$.
> \end{document}
> ```

I tried your second example:
```Python
import TexSoup
TexSoup.__version__
# '0.3.1'
soup = TexSoup.TexSoup(r"""
\documentclass{article} \begin{document} $\left[0~;~+ \infty\right[$. \end{document}
""")
```
and it fails for me too with `EOFError: [Line: 0, Offset: 28] "$" env expecting $. Reached end of file.`.

I'm not sure if I know what the underlying issue is, but some previous issues that might be related are:
https://github.com/alvinwan/TexSoup/issues/115 and https://github.com/alvinwan/TexSoup/issues/126

**Comment by ivanistheone** [comment]
I believe the source of the problem here is the `\infty` command sees the following `[` as if were the beginning of an optional argument and then fails because there is no matching `]`.

If you want to patch your local version of TexSoup, you could fix this by adding the line `    'infty': (0, 0),` to readers.py https://github.com/alvinwan/TexSoup/blob/master/TexSoup/reader.py#L29-L36
which will tell TexSoup that `\infty` takes zero optional args, and zero regular args and this will make your code examples work.  We'll need to think about enriching the "SIGNATURES" list eventually (see this comment  https://github.com/alvinwan/TexSoup/issues/115#issuecomment-708680500 )

A workaround you can use to prevent this breakage in the meantime is to insert a thin space `\;`right after the infty:
```Python
soup = TexSoup.TexSoup(r"""hello $[0~;~+ \infty\;[$. bye""")  # works fine
```

Or `\:` or `\,` whatever [space](http://www.emerson.emory.edu/services/latex/latex_119.html) you are willing to accept :)

**Comment by ntala** [comment]
Thank you for you quick answer.
I'm going to carefully read the pointed issues, but I must insist : the code you tried does not raise any exception on my computer.
I've got the same "version" of  TexSoup, but the version number was already "0.3.1" last august.
I installed it from the github repo a few hours ago. Maybe a part of the problem was solved since your version ?

**Comment by ivanistheone** [comment]
> but I must insist : the code you tried does not raise any exception on my computer.

Yes you are correct, the code
```
import TexSoup
soup = TexSoup.TexSoup(r"""
\documentclass{article} \begin{document} $\left[0~;~+ \infty\right[$. \end{document}
""")
```
works when the TexSoup version from github.

I guess the pypi version is missing some more recent fixes. Sorry for false alarm.

**Comment by ntala** [comment]
@ivanistheone 
You were right. After specifying `infty` signature, my problem is solved !
Now, I can begin processing my documents...
