### ISSUE TITLE
Differences in parsing `\hspace*` with 0.1.2

### ISSUE THREAD

**Issue by prabhuramachandran** [alvinwan/TexSoup#26]
Sorry for the flurry of issues.  Consider this:

```
s = TexSoup(r'''\hspace*{0.2in} hello \hspace*{2in} world''')
print(list(s.contents))
```
Version 0.1.2 Produces this:

`[\hspace, '*', RArg('0.2in'), ' hello ', \hspace, '*', RArg('2in'), ' world']`

Version 0.1 this:

`[\hspace*{0.2in}, ' hello ', \hspace*{2in}, ' world']`

I like the 0.1 behavior better, or am I doing something wrong?

**Comment by alvinwan** [comment]
No apologies needed - I really appreciate you sticking with it and reporting.

Mm, I see your other issue as well. I agree that the 0.1 `contents` is the better/right way to do it. I'll investigate.

In 0.1, I tokenize commands into 5 parts '\, command, {, arg, }` and in 0.1.2, I tokenize it into 4 `\command, {, arg, }`. This seems to have introduced a ton of issues, but I think this is the right way to tokenize, because `\` alone doesn't reveal whether it's an escape character or a command. I also did this for a different reason but I forget what. Do you have thoughts on this?

**Comment by alvinwan** [comment]
I figured out the issue. Previously, tokenizing `\command,` was incorrect, because the comma would be included in the command. I excluded all punctuation, so the asterisk was excluded as well. I've fixed that and now, the latest version on master correctly prints out

```
>>> from TexSoup import TexSoup
>>> s = TexSoup(r'''\hspace*{0.2in} hello \hspace*{2in} world''')
>>> print(list(s.contents))
[\hspace*{0.2in}, ' hello ', \hspace*{2in}, ' world']
```
