### ISSUE TITLE
Problems parsing [

### ISSUE THREAD

**Issue by seb-mtl** [alvinwan/TexSoup#79]
Hi,

Attached you can find a minimal **MVCE**. I have a scientific paper which contains several **\xyz{[}** or **\xyz{[0, 2)}**. There are no matching brackets so the parser assumes its a misalignment/mismatch.

```
from TexSoup import TexSoup

TexSoup(r"""
\\documentclass{article}
    \\usepackage[utf8]{inputenc}
\begin{document}
\\textbf{[}
\\end{document}
""")
```

> TypeError: Malformed argument. First and last elements must match a valid argument format. In this case, TexSoup could not find matching punctuation for: ['[', '}'].
> Common issues include: Unescaped special characters, mistyped closing punctuation, misalignment.
>

**Comment by LeCyberDucky** [comment]
I'm running into the same problem, I think. 

I'm trying to parse a file, but it breaks because it includes the following LaTeX code: 

`\begin{table}[H]
  \centering
\begin{tabular}{@{}llll@{}}
\toprule
Point                & Gradient                     & eig(H(x))              & Type          \\ \midrule
{[}0.087; 2.884{]}   & {[}4.273e-36; -1.657e-36{]}  & {[}75.508; -31.707{]}  & Saddle point  \\
{[}-3.073; -0.081{]} & {[}3.527e-38; 0{]}           & {[}72.435; -39.652{]}  & Saddle point  \\
{[}3.385; 0.074{]}   & {[}2.351e-38; 0{]}           & {[}97.548; -14.135{]}  & Saddle point  \\
{[}-0.271; -0.923{]} & {[}-1.763e-37; -1.763e-38{]} & {[}-16.066; -45.605{]} & Local maximum \\
{[}-2.805; 3.131{]}  & {[}2.939e-38; 1.176e-38{]}   & {[}80.550; 64.840{]}   & Local minimum \\
{[}-0.128; -1.954{]} & {[}1.328e-36; 2.233e-37{]}   & {[}20.284; -50.610{]}  & Saddle point  \\
{[}-3.779; -3.283{]} & {[}1.176e-38; 2.351e-38{]}   & {[}133.786; 70.714{]}  & Local minimum \\
{[}3.584; -1.848{]}  & {[}5.878e-39; -5.878e-39{]}  & {[}105.419; 28.691{]}  & Local minimum \\
{[}3; 2{]}           & {[}0; 0{]}                   & {[}82.284; 25.716{]}   & Local minimum \\ \bottomrule
\end{tabular}
\caption{Stationary points of \eqref{eq:E1_f(x)}}
\label{tab:E1_2_stat_points}
\end{table}`
